repos:
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
    - id: flake8
      args: ['--ignore=W503']
-   repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master
    hooks:
    - id: shellcheck
      exclude: ^epidose/device/setup/
-   repo: https://github.com/ansible/ansible-lint.git
    rev: master
    hooks:
      - id: ansible-lint
        entry: venv/bin/ansible-lint epidose/device/install_and_configure.yml epidose/back_end/deploy.yml
